language: python
python: 
  - "2.7"
branches:
  only:
    - travis
    - docker
env:
  global:
    - TFB_SERVER_HOST=127.0.0.1
    - TFB_CLIENT_HOST=127.0.0.1
    - TFB_DATABASE_HOST=127.0.0.1
    - TFB_CLIENT_USER=travis
    - TFB_DATABASE_USER=travis
    - TFB_CLIENT_IDENTITY_FILE=/home/travis/.ssh/id_rsa
    - TFB_DATABASE_IDENTITY_FILE=/home/travis/.ssh/id_rsa
  matrix:
    - TEST=go
    - TEST=nodejs
before_install:
  - sudo apt-get update
  - sudo apt-get install openssh-server
    # Run as travis use (who has passwordless sudo)
  - ssh-keygen -f /home/travis/.ssh/id_rsa -N '' -t rsa  
  - cat /home/travis/.ssh/id_rsa.pub > /home/travis/.ssh/authorized_keys
  - chmod 600 /home/travis/.ssh/authorized_keys
    # Setup the root account to be what TFB expects
  - mysql --user=root --execute="select Host,User,Password FROM mysql.user"
  - echo "Configuring mysql"
  - echo "USE mysql;\nUPDATE user SET password=PASSWORD('secret') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root
  - mysql --user=root --password=secret --execute="select Host,User,Password FROM mysql.user"
  - mysql -uroot -psecret < config/create.sql
  - mysql --user=root --password=secret --execute="select Host,User,Password FROM mysql.user"

install:
  - pip install docker-py
  - pip install coveralls
    # Install database software
  - coverage run --parallel-mode --omit installs,results toolset/run-tests.py --install database --log DEBUG --test ''
    # Install server prerequisites
  - coverage run --parallel-mode --omit installs,results toolset/run-tests.py --install server --log DEBUG --test ''
    # Install test code  
  - coverage run --parallel-mode --omit installs,results toolset/run-tests.py --install server --log DEBUG --test $TEST 
script: 
    # Run test verification 
  - coverage run --parallel-mode --omit installs,results toolset/run-tests.py --mode verify --log DEBUG --type json --test $TEST
after_success:
  - coverage combine
  - coverage report
  - coveralls
